
target("glfw")
    set_kind("static")
    add_defines("_GLFW_X11=1")
    add_includedirs("include/", {public=true})
    add_files("src/context.c")
    add_files("src/init.c")
    add_files("src/input.c")
    add_files("src/monitor.c")
    add_files("src/vulkan.c")
    add_files("src/window.c")
    add_files("src/x11_init.c")
    add_files("src/x11_monitor.c")
    add_files("src/x11_window.c")
    add_files("src/xkb_unicode.c")
    add_files("src/posix_time.c")
    add_files("src/posix_thread.c")
    add_files("src/glx_context.c")
    add_files("src/egl_context.c")
    add_files("src/osmesa_context.c")
    add_files("src/linux_joystick.c")

target("glad")
    set_kind("static")
    add_includedirs("deps/", {public=true})
    add_files("deps/glad_gl.c")
